### ISSUE TITLE
Backups via SSH rather than FTP?

### ISSUE THREAD

**Issue by sentur66413** [WolverineFan/dd-wrt.backupessential#1]
Is it possible to do backups with this script but via SSH instead of using FTP?

**Comment by WolverineFan** [comment]
Sure, should be rather easy.  Rather than sending all the files one by one like the script currently does, I'd probably modify it to create each of the tgz files, and then run one: 

scp -p *.tgz user@server:/path

Setting up a public key trust relationship would allow you to avoid entering a password each time.

Oh, and I'd be happy to accept a pull request if you want to share your version.
